AUTHOR='@zwpseudo'
VULN_NAME='phpMyAdmin Detected'
URI='/phpmyadmin/'
METHOD='GET'
MATCH='<title>phpMyAdmin '
SEVERITY='P5 - INFO'
CURL_OPTS="--user-agent '' -s -L --insecure"
SECONDARY_COMMANDS=''
GREP_OPTIONS='-i'